/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChartSymbolRouteImport } from './routes/chart.$symbol'

const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartSymbolRoute = ChartSymbolRouteImport.update({
  id: '/chart/$symbol',
  path: '/chart/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scanner': typeof ScannerRoute
  '/trades': typeof TradesRoute
  '/chart/$symbol': typeof ChartSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scanner': typeof ScannerRoute
  '/trades': typeof TradesRoute
  '/chart/$symbol': typeof ChartSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scanner': typeof ScannerRoute
  '/trades': typeof TradesRoute
  '/chart/$symbol': typeof ChartSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/scanner' | '/trades' | '/chart/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/scanner' | '/trades' | '/chart/$symbol'
  id: '__root__' | '/' | '/scanner' | '/trades' | '/chart/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScannerRoute: typeof ScannerRoute
  TradesRoute: typeof TradesRoute
  ChartSymbolRoute: typeof ChartSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart/$symbol': {
      id: '/chart/$symbol'
      path: '/chart/$symbol'
      fullPath: '/chart/$symbol'
      preLoaderRoute: typeof ChartSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScannerRoute: ScannerRoute,
  TradesRoute: TradesRoute,
  ChartSymbolRoute: ChartSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
